import os
import json
import asyncio
import datetime
import pandas as pd
import yfinance as yf
from pydantic import BaseModel, Field
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from app.tools.registry import registry

OUTPUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../data/charts"))

class ChartingInput(BaseModel):
    ticker: str = Field(description="The stock ticker symbol (e.g. AAPL)")
    overlays: list = Field(default_factory=list, description="List of technical overlays (lines, zones) generated by the agent")
    period: str = Field(default="3mo", description="Timeframe of historical data to fetch (e.g., '1mo', '3mo', '6mo', '1y')")

def fetch_data(symbol, period="3mo"):
    df = yf.Ticker(symbol).history(period=period)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    if len(df) == 0:
        raise Exception(f"No data found for {symbol}")
    df['EMA_20'] = df['Close'].ewm(span=20, adjust=False).mean()
    df['EMA_50'] = df['Close'].ewm(span=50, adjust=False).mean()
    if df.index.tz is not None:
        df.index = df.index.tz_localize(None)
    return df

def render_chart(df, spec, symbol):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True,
                        vertical_spacing=0.03,
                        subplot_titles=(f"{symbol} · Technical Analysis", "Volume"),
                        row_width=[0.2, 0.7])

    fig.add_trace(go.Candlestick(x=df.index, open=df['Open'], high=df['High'],
                                  low=df['Low'], close=df['Close'], name="Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['EMA_20'], line=dict(color='orange', width=1.5), name='EMA 20'), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['EMA_50'], line=dict(color='purple', width=1.5), name='EMA 50'), row=1, col=1)

    colors = ['green' if row['Close'] >= row['Open'] else 'red' for _, row in df.iterrows()]
    fig.add_trace(go.Bar(x=df.index, y=df['Volume'], marker_color=colors, name="Volume"), row=2, col=1)

    for ov in spec.get("overlays", []):
        # Support for old format vs new format
        kind = ov.get("kind") or ov.get("type")
        if kind in ("line", "support", "resistance", "trendline"):
            # Old format had x0/x1, new format might just be horizontal or sloped
            x0 = ov.get("x0", df.index[0])
            x1 = ov.get("x1", df.index[-1])
            y0 = ov.get("y0")
            y1 = ov.get("y1")
            if y0 is not None and y1 is not None:
                fig.add_shape(type="line", x0=x0, y0=y0, x1=x1, y1=y1,
                              line=dict(color=ov.get("color","white"), width=2, dash="dashdot"), row=1, col=1)
                fig.add_annotation(x=x1, y=y1, text=ov.get("reasoning",""), showarrow=False,
                                   yshift=10, font=dict(color=ov.get("color","white")), row=1, col=1)
        elif kind in ("zone", "volume_void"):
            is_void = kind == "volume_void"
            fc = ov.get("color", "purple" if is_void else "blue")
            x0 = ov.get("x0", df.index[0])
            x1 = ov.get("x1", df.index[-1])
            y0 = ov.get("y0")
            y1 = ov.get("y1")
            if y0 is not None and y1 is not None:
                fig.add_shape(type="rect", x0=x0, y0=y0, x1=x1, y1=y1,
                              line=dict(color=fc, width=1 if is_void else 0, dash="dot" if is_void else "solid"),
                              fillcolor=fc, opacity=0.3 if is_void else 0.2, row=1, col=1)
                fig.add_annotation(x=x0, y=y1, text=ov.get("reasoning",""), showarrow=False,
                                   yshift=10, font=dict(color=ov.get("color","white")), row=1, col=1)

    fig.update_layout(
        title=f"{symbol} · Technical Agent Overlays",
        template='plotly_dark', xaxis_rangeslider_visible=False, height=800)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    filename = f"{symbol}_{int(datetime.datetime.now().timestamp())}.html"
    out = os.path.join(OUTPUT_DIR, filename)
    fig.write_html(out)
    return filename


@registry.register(
    name="save_trading_chart",
    description="Render and save an HTML chart and JSON overlay data from the technical analyst agent.",
    parameters={
        "type": "object",
        "properties": {
            "ticker": {"type": "string", "description": "The stock ticker symbol"},
            "overlays": {"type": "array", "description": "JSON overlays array from the agent"},
            "period": {"type": "string", "description": "Timeframe of historical data to fetch (e.g., '1mo', '3mo', '6mo', '1y')"}
        },
        "required": ["ticker", "overlays"],
    },
    tier=1,
    source="data_sink",
    input_model=ChartingInput,
)
async def save_trading_chart(ticker: str, overlays: list = None, period: str = "3mo") -> str:
    """Takes JSON overlays and saves the chart files."""
    if overlays is None:
        overlays = []
        
    symbol = ticker.upper()
    df = await asyncio.to_thread(fetch_data, symbol, period)
    
    spec = {"overlays": overlays}
    
    filename = await asyncio.to_thread(render_chart, df, spec, symbol)
    chart_url = f"http://10.0.0.16:5591/charts/{filename}"
    
    # Save raw JSON for the frontend
    try:
        df_json = df.reset_index()
        df_json['Date'] = df_json['Date'].dt.strftime('%Y-%m-%d')
        
        latest_analysis = {
            "overlays": overlays,
            "filename": filename,
            "status": "success"
        }
        
        json_data = {
            "symbol": symbol,
            "period": period,
            "timestamp": int(datetime.datetime.now().timestamp()),
            "ohlcv": df_json[['Date', 'Open', 'High', 'Low', 'Close', 'Volume']].to_dict(orient='records'),
            "ema_20": df_json['EMA_20'].fillna(0).tolist(),
            "ema_50": df_json['EMA_50'].fillna(0).tolist(),
            "latest_analysis": latest_analysis
        }
        json_path = os.path.join(OUTPUT_DIR, f"{symbol}.json")
        with open(json_path, 'w') as f:
            json.dump(json_data, f)
    except Exception as e:
        print(f"Error saving JSON chart data: {e}")
        return f"Failed to save JSON: {e}"

    result = f"Successfully generated trading chart for {symbol}.\n\n"
    result += f"**Chart URL**: {chart_url}\n"
    
    return result
