# ============================================================
# Lazy Agent Service — Dockerfile (Proxy Harness)
# ============================================================

# ── Stage 1: Node.js TS Builder ──────────────────────────────
FROM node:22-slim AS node-build

RUN npm install -g pnpm

WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY .npmrc ./
# Rod's utilities-library is vendored as a local tarball rather than fetched
# from GitHub at build time — a private/renamed repo or a deleted commit would
# otherwise 404 here and break every deploy. Must be copied BEFORE the install
# so the file: dependency resolves. See vendor/README.md to refresh it.
COPY vendor ./vendor
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build
RUN pnpm prune --prod

# ── Stage 2: Runtime ──────────────────────────────────────────
FROM node:22-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy Node.js dependency and build files
COPY --from=node-build /app/node_modules ./node_modules
COPY --from=node-build /app/dist ./dist
COPY --from=node-build /app/package.json ./package.json

# Copy tool schemas dynamically generated by lazy-tool-service at build time
COPY tool_schemas.json ./tool_schemas.json

# Platform dashboard static assets (served at /dashboard)
COPY public ./public

# Expose port
EXPOSE 7778

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD wget --no-verbose --tries=1 -O /dev/null http://127.0.0.1:7778/health || exit 1

CMD ["node", "dist/boot.js"]
