/** Stateless execution capabilities carried through Prism's supported tool arguments.
 * Minted by our request proxy, attached by our model shim (never generated by
 * the model), checked and removed before local dispatch. Survives restarts.
 */
import { createHmac, timingSafeEqual } from "node:crypto";
import CONFIG from "../../config.ts";
import { stripMcpPrefix } from "./McpPrefix.ts";

export const TOOL_CONTEXT_ARG = "_lazy_trading_context";
const TAG = "TRADING_TOOL_CONTEXT_V1";
const markerRe = new RegExp(`<${TAG}>([A-Za-z0-9_.-]+)</${TAG}>`, "g");
export interface TradingToolContext {
  project: "vllm-trading-bot";
  agentName: string;
  cycleId: string;
  ticker: string;
  conversationId: string;
  allowedTools: string[];
  expiresAt: number;
}
function key(): string {
  const value = process.env.TRADING_TOOL_CONTEXT_KEY || process.env.TRADING_SERVICE_API_KEY || CONFIG.TRADING_SERVICE_API_KEY;
  if (!value || value === "change-me-local-dev") throw new Error("Trading tool signing key is not configured");
  return value;
}
export function signToolContext(context: TradingToolContext): string {
  const encoded = Buffer.from(JSON.stringify(context)).toString("base64url");
  return `${encoded}.${createHmac("sha256", key()).update("trading-tools-v1:" + encoded).digest("base64url")}`;
}
export function verifyToolContext(token: unknown): TradingToolContext {
  if (typeof token !== "string" || token.length > 32768) throw new Error("Missing trading tool authorization");
  const parts = token.split(".");
  if (parts.length !== 2) throw new Error("Invalid trading tool authorization");
  const expected = createHmac("sha256", key()).update("trading-tools-v1:" + parts[0]).digest();
  const supplied = Buffer.from(parts[1], "base64url");
  if (supplied.length !== expected.length || !timingSafeEqual(supplied, expected)) throw new Error("Invalid trading tool authorization");
  const ctx = JSON.parse(Buffer.from(parts[0], "base64url").toString());
  if (ctx.project !== "vllm-trading-bot" || typeof ctx.agentName !== "string" || !ctx.agentName ||
      typeof ctx.cycleId !== "string" || typeof ctx.ticker !== "string" ||
      typeof ctx.conversationId !== "string" || !ctx.conversationId ||
      !Array.isArray(ctx.allowedTools) || !ctx.allowedTools.every((t: unknown) => typeof t === "string") ||
      !Number.isFinite(ctx.expiresAt) || ctx.expiresAt <= Date.now()) throw new Error("Expired or malformed trading tool authorization");
  return ctx;
}
export function prepareToolContext(body: Record<string, any>): Record<string, any> {
  if (body.project !== "vllm-trading-bot") return body;
  const users = (body.messages || []).filter((m: any) => m.role === "user" && typeof m.content === "string");
  const task = users.map((m: any) => m.content).join("\n");
  const agentName = String(body.agent || "").toLowerCase().replace(/^custom_/, "");
  if (!agentName || !body.conversationId) throw new Error("Trading request requires agent and conversation identity");
  const context: TradingToolContext = {
    project: "vllm-trading-bot", agentName, conversationId: String(body.conversationId),
    // Cycle IDs are opaque harness identities, including observation and replay runs.
    // Preserve the complete heading value; never substitute the active production cycle.
    cycleId: task.match(/^## Cycle:[ \t]*([A-Za-z0-9][A-Za-z0-9_.:-]{0,159})[ \t]*\r?$/m)?.[1] || "",
    ticker: task.match(/^## Ticker:\s*([A-Z][A-Z0-9.-]{0,12})/m)?.[1] || "",
    allowedTools: [...new Set<string>((body.enabledTools || []).filter((t: unknown) => typeof t === "string").map(stripMcpPrefix))],
    expiresAt: Date.now() + 24 * 60 * 60 * 1000,
  };
  const token = signToolContext(context);
  return { ...body, systemPrompt: `<${TAG}>${token}</${TAG}>\n${body.systemPrompt || ""}` };
}
/** Remove gateway metadata from model input, including echoed prior tool calls. */
export function extractToolContext(body: Record<string, any>): { body: Record<string, any>; token?: string } {
  let token: string | undefined;
  const messages = (body.messages || []).map((m: any) => {
    let out = m;
    if (m.role === "system" && typeof m.content === "string") {
      const content = m.content.replace(markerRe, (_: string, found: string) => {
        verifyToolContext(found);
        if (token && token !== found) throw new Error("Conflicting trading tool identities");
        token = found;
        return "";
      });
      if (content.includes(`<${TAG}`) || content.includes(`</${TAG}`)) throw new Error("Malformed trading tool context marker");
      if (content !== m.content) out = { ...out, content };
    }
    if (Array.isArray(m.tool_calls)) {
      out = { ...out, tool_calls: m.tool_calls.map((call: any) => {
        try {
          const args = JSON.parse(call.function.arguments);
          if (!(TOOL_CONTEXT_ARG in args)) return call;
          delete args[TOOL_CONTEXT_ARG];
          return { ...call, function: { ...call.function, arguments: JSON.stringify(args) } };
        } catch { return call; }
      }) };
    }
    return out;
  });
  return { body: { ...body, messages }, token };
}
export function attachToolContext(argumentsText: string, token: string): string {
  const args = JSON.parse(argumentsText || "{}");
  if (!args || typeof args !== "object" || Array.isArray(args)) throw new Error("Tool arguments must be an object");
  return JSON.stringify({ ...args, [TOOL_CONTEXT_ARG]: token });
}
export function authorizeTradingTool(toolName: string, args: Record<string, unknown>) {
  const context = verifyToolContext(args[TOOL_CONTEXT_ARG]);
  if (!context.allowedTools.includes(stripMcpPrefix(toolName))) throw new Error(`Tool '${stripMcpPrefix(toolName)}' is not allowed for ${context.agentName}`);
  // Never let stateful cycle tools fall back to the global active cycle.
  if (/^(whiteboard_|request_peer_analysis)/.test(stripMcpPrefix(toolName)) && !context.cycleId) throw new Error("Cycle-scoped tool requires an explicit cycle identity");
  const clean = { ...args };
  delete clean[TOOL_CONTEXT_ARG];
  return { context, arguments: clean };
}

/** Stable authenticated connection scope for legacy non-trading MCP consumers.
 * It grants no trading-role authority; per-call capabilities always take precedence.
 */
export function signMcpClient(project: string): string {
  const value = Buffer.from(JSON.stringify({ project })).toString("base64url");
  return `${value}.${createHmac("sha256", key()).update("mcp-client-v1:" + value).digest("base64url")}`;
}
export function verifyMcpClient(token: unknown): string | undefined {
  try {
    if (typeof token !== "string" || token.length > 2048) return undefined;
    const [value, signature, extra] = token.split(".");
    if (!value || !signature || extra) return undefined;
    const expected = createHmac("sha256", key()).update("mcp-client-v1:" + value).digest();
    const supplied = Buffer.from(signature, "base64url");
    if (expected.length !== supplied.length || !timingSafeEqual(expected, supplied)) return undefined;
    const project = JSON.parse(Buffer.from(value, "base64url").toString()).project;
    return typeof project === "string" && project ? project : undefined;
  } catch { return undefined; }
}
