// Generated by scripts/export-chat-contract.mjs; do not edit.
export const EVENT_TYPES = ["run.admitted","run.started","run.created","message.delta","message.completed","tool.invoked","tool.called","tool.completed","tool.result","tool.failed","approval.required","approval.resolved","worker.dispatched","worker.completed","run.completed","run.failed","run.cancelled"] as const;
export type CanonicalEventType = typeof EVENT_TYPES[number];
export interface RuntimeEvent<T = Record<string, any>> {
  id: string;
  run_id: string;
  runId?: string;
  type: CanonicalEventType;
  timestamp: string;
  data: T;
}
