import MongoWrapper from "../wrappers/MongoWrapper.js";
import { MONGO_DB_NAME } from "../../config.js";
import { COLLECTIONS } from "../constants.js";
import EmbeddingService from "./EmbeddingService.js";
import AgentPersonaRegistry from "./AgentPersonaRegistry.js";
import logger from "../utils/logger.js";
import { getErrorMessage } from "../utils/ErrorHelpers.js";
// ────────────────────────────────────────────────────────────
// ConversationEmbeddingService
// ────────────────────────────────────────────────────────────
// Generates and persists a summary embedding on agent conversation
// documents to enable cross-session semantic search.
//
// Strategy (lean, zero extra LLM cost):
//   1. Read the conversation title from the document
//   2. Read the most recent memories stored for this conversationId
//   3. Concatenate title + memory contents → embed
//   4. $set { summaryEmbedding, summaryUpdatedAt } on the conversation doc
//
// Guards:
//   - Agent sessions only (not regular chat)
//   - Min 6 messages to avoid trivial conversations
//   - 5-minute cooldown since last summaryUpdatedAt
// ────────────────────────────────────────────────────────────
const MINIMUM_MESSAGES_FOR_EMBEDDING = 6;
const COOLDOWN_MILLISECONDS = 5 * 60 * 1000;
const ConversationEmbeddingService = {
    /**
     * Create an afterResponse hook handler for AgentHooks.
     * Runs as fire-and-forget (inspect category — errors are swallowed).
     */
    createHook() {
        return async (context, { messages }) => {
            ConversationEmbeddingService.generateAndPersist({
                conversationId: context.conversationId,
                agentConversationId: context.agentConversationId,
                project: context.project,
                username: context.username,
                agent: context.agent || null,
                traceId: context.traceId || null,
                messageCount: (messages || context.messages || []).length,
                endpoint: context.endpoint ||
                    "/agent",
            }).catch((error) => logger.error(`[ConversationEmbeddingService] Background embedding failed: ${getErrorMessage(error)}`));
        };
    },
    /**
     * Generate a summary embedding for the conversation and persist it.
     * Designed to be called fire-and-forget from the afterResponse hook.
     */
    async generateAndPersist({ conversationId, agentConversationId, project, username, agent, traceId, messageCount, endpoint, }) {
        if (!conversationId)
            return;
        // Agent sessions only — regular chat conversations don't need cross-session search
        if (!AgentPersonaRegistry.isAgentProject(project))
            return;
        // Minimum message threshold
        if (messageCount < MINIMUM_MESSAGES_FOR_EMBEDDING) {
            logger.info(`[ConversationEmbeddingService] Skipping — only ${messageCount} messages (min: ${MINIMUM_MESSAGES_FOR_EMBEDDING})`);
            return;
        }
        const database = MongoWrapper.getDb(MONGO_DB_NAME);
        if (!database)
            return;
        const conversationCollection = database.collection(COLLECTIONS.AGENT_CONVERSATIONS);
        // Cooldown check — don't re-embed if we did it recently
        const existingConversation = await conversationCollection.findOne({ id: conversationId, project, username }, { projection: { title: 1, summaryUpdatedAt: 1, compactionSummary: 1 } });
        if (!existingConversation)
            return;
        if (existingConversation.summaryUpdatedAt) {
            const lastUpdated = new Date(existingConversation.summaryUpdatedAt).getTime();
            const elapsed = Date.now() - lastUpdated;
            if (elapsed < COOLDOWN_MILLISECONDS) {
                logger.info(`[ConversationEmbeddingService] Skipping — cooldown active (${Math.round(elapsed / 1000)}s / ${COOLDOWN_MILLISECONDS / 1000}s)`);
                return;
            }
        }
        // Build the text to embed: title + compaction summary (if any) + recent memories
        const textParts = [];
        const conversationTitle = existingConversation.title;
        if (conversationTitle) {
            textParts.push(conversationTitle);
        }
        // Use compaction summary if available (free — already generated by CompactionService)
        const compactionSummary = existingConversation.compactionSummary;
        if (compactionSummary) {
            textParts.push(compactionSummary);
        }
        // Fetch memories linked to this conversation
        const memoryCollection = database.collection(COLLECTIONS.MEMORIES);
        const linkedMemories = await memoryCollection
            .find({ conversationId, agent: agent || "CODING" }, { projection: { title: 1, content: 1 } })
            .sort({ createdAt: -1 })
            .limit(20)
            .toArray();
        if (linkedMemories.length > 0) {
            const memoryTextBlocks = linkedMemories
                .map((memory) => {
                const memoryTitle = memory.title;
                const memoryContent = memory.content;
                return memoryTitle
                    ? `${memoryTitle}: ${memoryContent}`
                    : memoryContent || "";
            })
                .filter(Boolean);
            textParts.push(...memoryTextBlocks);
        }
        // If we have nothing meaningful to embed, skip
        if (textParts.length === 0) {
            logger.info(`[ConversationEmbeddingService] Skipping — no title, summary, or memories to embed`);
            return;
        }
        const embeddingSourceText = textParts.join("\n");
        // Truncate to ~2000 chars to keep embedding costs low
        const truncatedText = embeddingSourceText.length > 2000
            ? embeddingSourceText.slice(0, 2000)
            : embeddingSourceText;
        // Generate the embedding
        const summaryEmbedding = await EmbeddingService.embed(truncatedText, {
            source: "conversation-summary",
            project,
            endpoint: endpoint || "/agent",
            traceId,
            conversationId,
            agentConversationId: agentConversationId || "",
            agent,
        });
        // Persist on the conversation document
        await conversationCollection.updateOne({ id: conversationId, project, username }, {
            $set: {
                summaryEmbedding,
                summaryUpdatedAt: new Date().toISOString(),
            },
        });
        logger.info(`[ConversationEmbeddingService] Embedded conversation ${conversationId} ` +
            `(${textParts.length} text parts, ${linkedMemories.length} memories, ` +
            `${truncatedText.length} chars)`);
    },
    /**
     * Persist a compaction summary on the conversation document.
     * Called by the harness when CompactionService produces a summary.
     * This summary is later used as an embedding source — zero extra LLM cost.
     */
    async persistCompactionSummary(conversationId, project, username, summaryText) {
        const database = MongoWrapper.getDb(MONGO_DB_NAME);
        if (!database)
            return;
        const collection = AgentPersonaRegistry.isAgentProject(project)
            ? database.collection(COLLECTIONS.AGENT_CONVERSATIONS)
            : database.collection(COLLECTIONS.MODEL_CONVERSATIONS);
        await collection.updateOne({ id: conversationId, project, username }, {
            $set: {
                compactionSummary: summaryText,
                compactionSummaryUpdatedAt: new Date().toISOString(),
            },
        });
        logger.info(`[ConversationEmbeddingService] Persisted compaction summary on ${conversationId} (${summaryText.length} chars)`);
    },
};
export default ConversationEmbeddingService;
//# sourceMappingURL=ConversationEmbeddingService.js.map